//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EX_8_Rest_ASP_NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int ID { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public string color { get; set; }
    }
}
